### ISSUE TITLE
If incorreto para visualização de dados

### ISSUE THREAD

**Issue by Romulo-Anjos** [RobsonT/Streamlit-app#2]
https://github.com/RobsonT/Streamlit-app/blob/79b8e9461d56e3854a4b69f5dac9f927b635c5e7/main.py#L135

Robson, parabéns pelo aplicativo que vc criou com as aulas do Codenation. To aqui trabalhando pra finalizar o meu. 
Um negócio que eu vi que no seu código vc coloca na sidebar pra escolher o nome "Visualização dos Dados", mas no if da linha 135, vc coloca a palavra "Gráficos" acho que precisa ajustar os nomes para ficarem iguais porque quando abro seu aplicativo, não aparece a seção de visualização.

**Comment by RobsonT** [comment]
> https://github.com/RobsonT/Streamlit-app/blob/79b8e9461d56e3854a4b69f5dac9f927b635c5e7/main.py#L135
> 
> Robson, parabéns pelo aplicativo que vc criou com as aulas do Codenation. To aqui trabalhando pra finalizar o meu.
> Um negócio que eu vi que no seu código vc coloca na sidebar pra escolher o nome "Visualização dos Dados", mas no if da linha 135, vc coloca a palavra "Gráficos" acho que precisa ajustar os nomes para ficarem iguais porque quando abro seu aplicativo, não aparece a seção de visualização.

Obrigado por me avisar, tinha alterado a opção e me esqueci de atualizar no if. Já corregi o problema.
